# Generated by Django 5.0.6 on 2024-11-18 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photogallery_description_photogallery_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='photogallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.photogallery')),
            ],
        ),
    ]
