# Generated by Django 5.0.6 on 2024-11-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_photo_gallery_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
