# Generated by Django 5.0.6 on 2024-11-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
