# Generated by Django 5.0.6 on 2024-11-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinquiry',
            name='inquiry_date',
        ),
    ]
